### PR TITLE
Update Server.py

### PR DESCRIPTION
**Pull request by vaniisgh**
changes in the Server file to support the changes in the config.

### CODE REVIEW

**Comment by uniqueg** [comment]
Thanks. I had just added a hotfix branch to revert the changes in the config. Does this work now? Did you try it out?

**Comment by vaniisgh** [comment]
thanks, I just realised ...
ya I have checked it 👍

**Comment by uniqueg** [comment]
But good example on why to use different branches for different changes:
- Dockerizing the app (`Dockerfile`, `docker-compose.yaml`, _required_ changes to `host` and `port` config values) => one feature branch
- Changing where a config file is located and where it is read => _another_ feature branch

**Comment by vaniisgh** [comment]
I think I better understand how to define each feature now. Will try to implement the same now on. thank you

**Pull request merged**
